"""Export static JSON artifacts for the Next.js frontend.

Reads from the latest pipeline Parquet artifacts produced by ``andria run``
and writes 7 schema-aligned JSON files to ``frontend/public/data/``.

The frontend reads these files at build/request time — no backend API
call required at runtime. Run this after every pipeline execution to
refresh the live dashboard.

Usage::
    python export_static_artifacts.py

If no pipeline artifacts exist, falls back to the demo data generated by
``python scripts/generate_demo_artifacts.py``.
"""
from __future__ import annotations

import hashlib
import json
import subprocess
from datetime import UTC, datetime
from pathlib import Path

PROJECT_ROOT = Path(__file__).parent
ARTIFACTS = PROJECT_ROOT / "artifacts"
OUT_DIR = PROJECT_ROOT / "frontend" / "public" / "data"


# helpers

def _read_parquet(path: Path):
    """Return a Polars DataFrame or None."""
    if not path.exists():
        return None
    try:
        import polars as pl
        return pl.read_parquet(path)
    except Exception as exc:
        print(f"  [WARN] {path.name}: {exc}")
        return None


def _latest_run_file(subdir: str, filename: str) -> Path | None:
    """Find the most-recently-modified file across all run directories."""
    runs = ARTIFACTS / "runs"
    if not runs.exists():
        return None
    dirs = sorted(runs.iterdir(), key=lambda p: p.stat().st_mtime, reverse=True)
    for d in dirs:
        candidate = d / subdir / filename
        if candidate.exists():
            return candidate
    return None


def _git_commit() -> str:
    import os
    env_sha = os.environ.get("GIT_SHA", "").strip()
    if env_sha:
        return env_sha
    sha_file = PROJECT_ROOT / ".git_sha"
    if sha_file.exists():
        content = sha_file.read_text().strip()
        return content.split("=", 1)[1].strip() if content.startswith("GIT_SHA=") else content
    try:
        result = subprocess.run(
            ["git", "rev-parse", "--short", "HEAD"],
            capture_output=True, text=True, timeout=5,
        )
        return result.stdout.strip() if result.returncode == 0 else "unknown"
    except Exception:
        return "unknown"


def _write(name: str, data: dict) -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    path = OUT_DIR / name
    path.write_text(json.dumps(data, indent=2, default=str), encoding="utf-8")
    size_kb = path.stat().st_size / 1024
    print(f"  OK  {name:<22} {size_kb:6.1f} KB")


def _file_sha16(name: str) -> str:
    p = OUT_DIR / name
    return hashlib.sha256(p.read_bytes()).hexdigest()[:16] if p.exists() else "pending"


# ── exporters ─────────────────────────────────────────────────────────────────

def export_signals(run_id: str) -> None:
    path = (
        _latest_run_file("signals", "racs_signals.parquet")
        or ARTIFACTS / "signals" / "racs_signals.parquet"
    )
    df = _read_parquet(path) if path else None

    if df is not None:
        import polars as pl
        cols = [
            c for c in [
                "quarter", "cusip", "ticker", "activist_buyers", "strong_buys",
                "total_activist_value", "total_funds", "conviction_raw",
                "crowding_penalty", "racs_score", "regime_label",
                "regime_adjusted_racs",
            ]
            if c in df.columns
        ]
        top = df.sort("regime_adjusted_racs", descending=True).head(500).select(cols)
        top = top.with_row_index("rank", offset=1)
        data: dict = {
            "generated_at": datetime.now(UTC).isoformat(),
            "run_id": run_id,
            "provenance_quality": None,
            "validation_passed": None,
            "total_signals": df.height,
            "data_quarters": (
                sorted(df["quarter"].unique().to_list()) if "quarter" in df.columns else []
            ),
            "signals": top.to_dicts(),
        }
    else:
        data = _demo_fallback("signals.json", "signals", run_id)

    _write("signals.json", data)


def export_regimes(run_id: str) -> None:
    path = (
        _latest_run_file("regime", "regime_timeseries.parquet")
        or ARTIFACTS / "regime" / "regime_timeseries.parquet"
    )
    df = _read_parquet(path) if path else None

    if df is not None:
        import polars as pl
        sorted_df = df.sort("date", descending=True)
        current = sorted_df.head(1).to_dicts()[0] if len(sorted_df) > 0 else {}
        history = df.sort("date").to_dicts()
        dist = []
        if "regime_label" in df.columns:
            dist = (
                df.group_by("regime_label")
                .agg(pl.len().alias("count"))
                .with_columns((pl.col("count") / df.height).round(3).alias("pct"))
                .sort("count", descending=True)
                .to_dicts()
            )
        transition_matrix = _empirical_transition_matrix(df) if "regime_label" in df.columns else None

        data: dict = {
            "generated_at": datetime.now(UTC).isoformat(),
            "run_id": run_id,
            "total_observations": df.height,
            "current": current,
            "history": history,
            "distribution": dist,
        }
        if transition_matrix is not None:
            data["transition_matrix"] = transition_matrix
    else:
        data = _demo_fallback("regimes.json", "regimes", run_id)

    _write("regimes.json", data)


def _empirical_transition_matrix(df) -> dict | None:
    """Row-stochastic P(next quarter regime | current regime), estimated from the
    actual observed sequence of HMM regime labels -- not a fabricated matrix.
    """
    ordered = df.sort("date")
    seq = ordered["regime_label"].to_list()
    if len(seq) < 2:
        return None

    canonical = ["Goldilocks", "Recovery", "Rate_Shock", "Recession_Fear"]
    seen = list(dict.fromkeys(seq))
    labels = [lbl for lbl in canonical if lbl in seen] + [lbl for lbl in seen if lbl not in canonical]

    idx = {lbl: i for i, lbl in enumerate(labels)}
    counts = [[0] * len(labels) for _ in labels]
    for a, b in zip(seq[:-1], seq[1:], strict=True):
        counts[idx[a]][idx[b]] += 1

    matrix = []
    for row in counts:
        total = sum(row)
        matrix.append([round(c / total, 4) for c in row] if total > 0 else [0.0] * len(row))

    return {"labels": labels, "matrix": matrix}


def export_clusters(run_id: str) -> None:
    path = (
        _latest_run_file("clusters", "clustered_managers.parquet")
        or ARTIFACTS / "clusters" / "clustered_managers.parquet"
    )
    df = _read_parquet(path) if path else None

    if df is not None:
        import polars as pl
        total = df.height
        archetype_meta = []
        if "archetype_label" in df.columns:
            archetype_meta = (
                df.group_by("archetype_label")
                .agg(pl.len().alias("count"))
                .with_columns((pl.col("count") / total).round(3).alias("pct"))
                .sort("count", descending=True)
                .to_dicts()
            )
        umap_cols = [
            c for c in ["umap_1", "umap_2", "archetype_label", "cluster_id"]
            if c in df.columns
        ]
        sample = (
            df.select(umap_cols)
            .sample(min(2000, total), seed=42)
            .rename({"umap_1": "umap_x", "umap_2": "umap_y"})
            .to_dicts()
        ) if umap_cols else []

        diag_path = (
            _latest_run_file("clusters", "diagnostics.json")
            or ARTIFACTS / "clusters" / "diagnostics.json"
        )
        diagnostics: dict = {}
        if diag_path and diag_path.exists():
            try:
                diagnostics = json.loads(diag_path.read_text())
            except Exception as exc:
                print(f"  [WARN] clusters diagnostics.json: {exc}")

        data: dict = {
            "generated_at": datetime.now(UTC).isoformat(),
            "run_id": run_id,
            "total_managers": total,
            "n_archetypes": len(archetype_meta),
            "algorithm": "HDBSCAN",
            "embedding": "UMAP(n_components=2)",
            "archetypes": archetype_meta,
            "umap_sample": sample,
            **diagnostics,
        }
    else:
        data = _demo_fallback("clusters.json", "clusters", run_id)

    _write("clusters.json", data)


def export_portfolio(run_id: str) -> None:
    path = (
        _latest_run_file("backtest", "trade_ledger.parquet")
        or ARTIFACTS / "backtest" / "trade_ledger.parquet"
    )
    df = _read_parquet(path) if path else None

    if df is not None:
        import polars as pl
        n_positions = df.n_unique("cusip") if "cusip" in df.columns else 0
        top_holdings = []
        if "cusip" in df.columns and "net_fwd_return" in df.columns:
            top_raw = (
                df.group_by("cusip")
                .agg(
                    pl.col("net_fwd_return").mean().alias("mean_return"),
                    pl.len().alias("n_trades"),
                )
                .sort("mean_return", descending=True)
                .head(10)
                .to_dicts()
            )
            top_holdings = [
                {"rank": i + 1, "cusip": r["cusip"], "mean_return": round(r["mean_return"], 4)}
                for i, r in enumerate(top_raw)
            ]
        data: dict = {
            "generated_at": datetime.now(UTC).isoformat(),
            "run_id": run_id,
            "summary": {"n_positions": n_positions},
            "top_holdings": top_holdings,
        }
    else:
        data = _demo_fallback("portfolio.json", "portfolio", run_id)

    _write("portfolio.json", data)


def export_validation(run_id: str) -> None:
    path = (
        _latest_run_file("validation", "evaluation_gate.json")
        or ARTIFACTS / "validation" / "evaluation_gate.json"
    )
    if path and path.exists():
        raw = json.loads(path.read_text())
        raw.update({"generated_at": datetime.now(UTC).isoformat(), "run_id": run_id})
        _write("validation.json", raw)
    else:
        _write("validation.json", _demo_fallback("validation.json", "validation", run_id))


def export_backtest(run_id: str) -> None:
    path = (
        _latest_run_file("backtest", "walk_forward_summary.json")
        or ARTIFACTS / "backtest" / "walk_forward_summary.json"
    )
    if path and path.exists():
        raw = json.loads(path.read_text())
        raw.update({"generated_at": datetime.now(UTC).isoformat(), "run_id": run_id})
        _write("backtest.json", raw)
    else:
        _write("backtest.json", _demo_fallback("backtest.json", "backtest", run_id))


def _real_data_vintage() -> dict:
    """Derive data_vintage from the actual ingested datasets rather than
    hardcoding it -- the previous hardcoded "2024_Q4" / 116,000,000 values
    silently went stale (and were simply wrong) the moment a real ingestion
    covered a different date range or row count."""
    edgar_dir = PROJECT_ROOT / "dataset" / "processed" / "edgar"
    fred_path = PROJECT_ROOT / "dataset" / "processed" / "FRED_preprocess.parquet"
    vintage = {
        "edgar_through": None,
        "fred_through": None,
        "total_filings_processed": None,
        "total_managers": None,
        "total_cusips": None,
        "source": "SEC EDGAR 13F",
    }
    try:
        import duckdb
        if edgar_dir.exists() and any(edgar_dir.rglob("*.parquet")):
            con = duckdb.connect()
            con.execute("SET memory_limit='2GB'")
            row = con.execute(f"""
                SELECT MAX(source_quarter), COUNT(*),
                       COUNT(DISTINCT FILINGMANAGER_NAME), COUNT(DISTINCT CUSIP)
                FROM read_parquet('{edgar_dir}/**/*.parquet', hive_partitioning=true)
            """).fetchone()
            if row:
                vintage["edgar_through"] = row[0]
                vintage["total_filings_processed"] = row[1]
                vintage["total_managers"] = row[2]
                vintage["total_cusips"] = row[3]
            con.close()
        if fred_path.exists():
            con = duckdb.connect()
            fred_max = con.execute(
                f"SELECT MAX(observation_date) FROM read_parquet('{fred_path}')"
            ).fetchone()
            if fred_max:
                vintage["fred_through"] = str(fred_max[0])
            con.close()
    except Exception as exc:
        print(f"  [WARN] could not derive real data_vintage: {exc}")
    return vintage


def _recent_runs(limit: int = 5) -> list[dict]:
    """Recent pipeline runs, read from the real manifest.json each `andria run`
    invocation writes to artifacts/runs/{run_id}/ -- not a fabricated run log."""
    runs_dir = ARTIFACTS / "runs"
    if not runs_dir.exists():
        return []
    manifests = sorted(runs_dir.glob("*/manifest.json"), key=lambda p: p.stat().st_mtime, reverse=True)
    out = []
    for path in manifests[:limit]:
        try:
            m = json.loads(path.read_text())
        except Exception:
            continue
        out.append({
            "run_id": m.get("run_id"),
            "stage": m.get("stage"),
            "status": m.get("status"),
            "started_at": m.get("started_at"),
            "completed_at": m.get("completed_at"),
            "git_sha": m.get("git_sha"),
        })
    return out


def export_metadata(run_id: str) -> None:
    artifact_names = [
        "signals.json", "regimes.json", "clusters.json",
        "portfolio.json", "validation.json", "backtest.json",
    ]
    vintage = _real_data_vintage()
    if vintage["edgar_through"] is None:
        vintage = {
            "edgar_through": "2024_Q4",
            "fred_through": "2024-12-31",
            "total_filings_processed": 116_000_000,
            "source": "SEC EDGAR 13F (2000-2024) [placeholder -- no real ingestion found]",
        }
    _write("metadata.json", {
        "generated_at": datetime.now(UTC).isoformat(),
        "run_id": run_id,
        "git_commit": _git_commit(),
        "pipeline_version": "4.16",
        "data_vintage": vintage,
        "recent_runs": _recent_runs(),
        "artifact_hashes": {n: _file_sha16(n) for n in artifact_names},
    })


# ── demo fallback ─────────────────────────────────────────────────────────────

def _demo_fallback(filename: str, kind: str, run_id: str) -> dict:
    """Return existing demo artifact, or a minimal placeholder."""
    demo_path = OUT_DIR / filename
    if demo_path.exists():
        try:
            data = json.loads(demo_path.read_text())
            data["run_id"] = run_id
            return data
        except Exception:
            pass
    return {
        "generated_at": datetime.now(UTC).isoformat(),
        "run_id": run_id,
        "_note": f"Run 'andria run' then 'python export_static_artifacts.py' to populate {kind} data.",
    }


# ── main ──────────────────────────────────────────────────────────────────────

def main() -> None:
    try:
        from andria.core.config import get_settings
        run_id = get_settings().run_id
    except Exception:
        import uuid
        run_id = datetime.now(UTC).strftime("%Y%m%dT%H%M%S") + "_" + uuid.uuid4().hex[:6]

    print(f"Exporting static artifacts  run_id={run_id}")
    print(f"Output -> {OUT_DIR}")
    if not ARTIFACTS.exists():
        print("  [INFO] No pipeline artifacts found — using demo data.")
    print()

    export_signals(run_id)
    export_regimes(run_id)
    export_clusters(run_id)
    export_portfolio(run_id)
    export_validation(run_id)
    export_backtest(run_id)
    export_metadata(run_id)

    print("\nExport complete.")


if __name__ == "__main__":
    main()
