# Data Pipeline Configurations
data:
  min_valid_date: "2010-01-01"
  top_n_tickers: 10000
  exposure_imputation_value: "SH"
  paths:
    edgar: "dataset/raw/edgar_*.parquet"
    fred: "dataset/raw/fred_*.parquet"
    ofr: "dataset/raw/ofr_*.parquet"
