"""Monte Carlo Robustness Testing (Phase 4.8).

Tests whether the strategy's Sharpe ratio survives randomness by comparing
it against distributions generated by:

1. **Bootstrap resampling** — trades sampled with replacement (N=1000).
   Tests sampling variability; a p-value is computed as P(resampled Sharpe < 0).

2. **Randomized entry timing** — entry dates shuffled while keeping trade
   returns fixed. Tests whether signal *timing* contributes, or whether
   the strategy is just capturing a general market drift.

3. **Regime permutation** — regime labels randomly reassigned.
   Tests whether regime-conditional outperformance is real or random.

Usage::

    from andria.backtest.monte_carlo import MonteCarloTester
    tester = MonteCarloTester(n_simulations=1000, seed=42)
    results = tester.run_all(ledger)
    tester.print_summary(results)
"""

from __future__ import annotations

from dataclasses import dataclass

import numpy as np
import polars as pl

from andria.backtest.diagnostics import calculate_sharpe
from andria.core.logging import get_logger

logger = get_logger(__name__)


@dataclass
class MonteCarloResult:
    """Results from a single Monte Carlo test."""

    test_name: str
    observed_sharpe: float
    simulated_sharpes: list[float]
    p_value: float          # P(simulated Sharpe >= observed)
    sharpe_5pct: float
    sharpe_50pct: float
    sharpe_95pct: float

    @property
    def is_significant(self) -> bool:
        """True if observed Sharpe is statistically above the null distribution."""
        return self.p_value < 0.05


class MonteCarloTester:
    """Bootstrap and permutation robustness tests for the trade ledger.

    Args:
        n_simulations: Number of Monte Carlo draws per test.
        seed:          Random seed for reproducibility.
    """

    def __init__(self, n_simulations: int = 1000, seed: int = 42) -> None:
        self.n_simulations = n_simulations
        self._rng = np.random.default_rng(seed)

    def bootstrap_sharpe(self, ledger: pl.DataFrame) -> MonteCarloResult:
        """Bootstrap the Sharpe ratio distribution via trade resampling.

        Samples trades with replacement N times and computes the Sharpe ratio
        on each bootstrap sample. The p-value is P(Sharpe <= 0 in bootstrap).

        Args:
            ledger: Trade ledger with ``net_fwd_return`` column.

        Returns:
            MonteCarloResult with the bootstrap distribution.
        """
        returns = ledger["net_fwd_return"].to_numpy()
        observed = float(calculate_sharpe(ledger["net_fwd_return"]))
        n = len(returns)

        sim_sharpes: list[float] = []
        for _ in range(self.n_simulations):
            sample = self._rng.choice(returns, size=n, replace=True)
            series = pl.Series(sample)
            sim_sharpes.append(float(calculate_sharpe(series)))

        arr = np.array(sim_sharpes)
        p_val = float(np.mean(arr <= 0))  # fraction of sims with non-positive Sharpe

        logger.info(
            "bootstrap_complete",
            observed_sharpe=round(observed, 3),
            p_value_sharpe_le_zero=round(p_val, 3),
        )

        return MonteCarloResult(
            test_name="bootstrap_resampling",
            observed_sharpe=observed,
            simulated_sharpes=sim_sharpes,
            p_value=p_val,
            sharpe_5pct=float(np.percentile(arr, 5)),
            sharpe_50pct=float(np.percentile(arr, 50)),
            sharpe_95pct=float(np.percentile(arr, 95)),
        )

    def randomized_entry_timing(self, ledger: pl.DataFrame) -> MonteCarloResult:
        """Test whether signal timing matters by shuffling entry dates.

        Shuffles the ``exec_date`` column while keeping returns in place.
        If the strategy's Sharpe does not significantly exceed the shuffled
        distribution, signal timing adds no value.

        Args:
            ledger: Trade ledger with ``net_fwd_return`` column.

        Returns:
            MonteCarloResult comparing observed vs. timing-randomized Sharpe.
        """
        returns = ledger["net_fwd_return"].to_numpy()
        observed = float(calculate_sharpe(ledger["net_fwd_return"]))

        sim_sharpes: list[float] = []
        for _ in range(self.n_simulations):
            # Shuffle returns (equivalent to shuffling timing with respect to returns)
            shuffled = self._rng.permutation(returns)
            series = pl.Series(shuffled)
            sim_sharpes.append(float(calculate_sharpe(series)))

        arr = np.array(sim_sharpes)
        # Two-sided: P(|sim| >= |observed|)
        p_val = float(np.mean(np.abs(arr) >= abs(observed)))

        logger.info(
            "timing_permutation_complete",
            observed_sharpe=round(observed, 3),
            p_value=round(p_val, 3),
        )

        return MonteCarloResult(
            test_name="randomized_entry_timing",
            observed_sharpe=observed,
            simulated_sharpes=sim_sharpes,
            p_value=p_val,
            sharpe_5pct=float(np.percentile(arr, 5)),
            sharpe_50pct=float(np.percentile(arr, 50)),
            sharpe_95pct=float(np.percentile(arr, 95)),
        )

    def regime_permutation(self, ledger: pl.DataFrame) -> MonteCarloResult | None:
        """Test whether regime-conditional performance is real or random.

        Randomly reassigns regime labels to trades and computes the variance
        of per-regime mean returns. If the real regime variance is not
        significantly above the permuted distribution, regime conditioning
        adds no explanatory value.

        Args:
            ledger: Trade ledger with ``regime_label`` and ``net_fwd_return``.

        Returns:
            MonteCarloResult, or None if ``regime_label`` column is absent.
        """
        if "regime_label" not in ledger.columns:
            logger.warning("regime_permutation_skipped", reason="No regime_label column")
            return None

        returns = ledger["net_fwd_return"].to_numpy()
        regimes = ledger["regime_label"].to_numpy()
        observed_sharpe = float(calculate_sharpe(ledger["net_fwd_return"]))

        # Statistic: variance of per-regime mean returns (higher = more differentiation)
        unique_regimes = np.unique(regimes)
        def regime_variance(r_labels: np.ndarray) -> float:
            means = [returns[r_labels == reg].mean() for reg in unique_regimes if (r_labels == reg).sum() > 0]
            return float(np.var(means)) if means else 0.0

        observed_var = regime_variance(regimes)
        sim_vars: list[float] = []
        sim_sharpes: list[float] = []

        for _ in range(self.n_simulations):
            shuffled_regimes = self._rng.permutation(regimes)
            sim_vars.append(regime_variance(shuffled_regimes))
            sim_sharpes.append(observed_sharpe)  # Sharpe is regime-agnostic here

        arr = np.array(sim_vars)
        p_val = float(np.mean(arr >= observed_var))

        logger.info(
            "regime_permutation_complete",
            observed_regime_variance=round(observed_var, 6),
            p_value=round(p_val, 3),
        )

        return MonteCarloResult(
            test_name="regime_permutation",
            observed_sharpe=observed_var,      # using variance as the test statistic
            simulated_sharpes=sim_vars,
            p_value=p_val,
            sharpe_5pct=float(np.percentile(arr, 5)),
            sharpe_50pct=float(np.percentile(arr, 50)),
            sharpe_95pct=float(np.percentile(arr, 95)),
        )

    def run_all(self, ledger: pl.DataFrame) -> list[MonteCarloResult]:
        """Run all three Monte Carlo tests."""
        results: list[MonteCarloResult] = [
            self.bootstrap_sharpe(ledger),
            self.randomized_entry_timing(ledger),
        ]
        regime_result = self.regime_permutation(ledger)
        if regime_result is not None:
            results.append(regime_result)
        return results

    @staticmethod
    def print_summary(results: list[MonteCarloResult]) -> None:
        """Print a formatted summary of all Monte Carlo results."""
        print(f"\n{'Test':<30} {'Observed':>10} {'5th%':>8} {'Median':>8} {'95th%':>8} {'p-value':>9} {'Sig?':>5}")
        print("-" * 82)
        for r in results:
            sig = "✓" if r.is_significant else "✗"
            print(
                f"{r.test_name:<30} {r.observed_sharpe:>10.4f} "
                f"{r.sharpe_5pct:>8.4f} {r.sharpe_50pct:>8.4f} {r.sharpe_95pct:>8.4f} "
                f"{r.p_value:>9.4f} {sig:>5}"
            )
